# Generated by https://smithery.ai. See: https://smithery.ai/docs/build/project-config
FROM python:3.13-slim

# Set working directory
WORKDIR /app

# Copy dependency specification
COPY pyproject.toml .

# Install dependencies
RUN pip install --no-cache-dir mcp[cli]>=1.5.0 httpx>=0.28.1 requests>=2.32.3

# Copy application code
COPY . .

# Default command to start the MCP server
CMD ["python", "Internet_search.py"]
